// Alerts API — matches the provided endpoint contract exactly:
//   GET   /v1/alerts
//   GET   /v1/alerts/{alertId}
//   PATCH /v1/alerts/{alertId}/acknowledge
//   PATCH /v1/alerts/{alertId}/resolve
//
// Alerts are never created directly by users — they're generated by the
// platform after policy evaluation — so there's no POST here.
//
// GET /v1/alerts returns AlertSummaryResource items: only
// { id, prediction_id, severity, status, created_at, reasons } — no
// agent_name, risk_score, or confidence at the list level. The fuller
// AlertDetailResource (with nested `prediction` and `observation`) is only
// returned by GET /v1/alerts/{alertId}.
//
// As with Agents, single-resource endpoints unwrap the `{ data: ... }`
// envelope here so callers get a plain object; the list endpoint keeps its
// `{ data, pagination }` envelope.

import { apiFetch, toQueryString, MOCK_MODE, ApiError } from "../apiClient.js";
import { db } from "../mockDb.js";

function delay(ms = 350) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

// GET /v1/alerts — query params: status, severity, page, per_page (no
// `sort`; the Backend always orders by created_at descending).
export async function listAlerts(params = {}) {
  if (MOCK_MODE) {
    await delay();
    return db.getAlerts(params);
  }
  return apiFetch(`/alerts${toQueryString(params)}`);
}

// GET /v1/alerts/{alertId} — full AlertDetailResource, composed with its
// Prediction and a minimal Observation embed.
export async function getAlert(alertId) {
  if (MOCK_MODE) {
    await delay();
    const alert = db.getAlert(alertId);
    if (!alert) throw new ApiError("NOT_FOUND", "Alert not found.");
    return alert;
  }
  const res = await apiFetch(`/alerts/${alertId}`);
  return res.data;
}

// PATCH /v1/alerts/{alertId}/acknowledge — no body; acknowledged_by is
// always the caller's own user id, server-derived. Only valid from OPEN.
// Response: { id, status, acknowledged_at, acknowledged_by }.
export async function acknowledgeAlert(alertId) {
  if (MOCK_MODE) {
    await delay();
    return db.acknowledgeAlert(alertId);
  }
  const res = await apiFetch(`/alerts/${alertId}/acknowledge`, { method: "PATCH" });
  return res.data;
}

// PATCH /v1/alerts/{alertId}/resolve — no body; valid from OPEN or
// ACKNOWLEDGED (skip-ahead allowed). RESOLVED is terminal.
// Response: { id, status, resolved_at, resolved_by }.
export async function resolveAlert(alertId) {
  if (MOCK_MODE) {
    await delay();
    return db.resolveAlert(alertId);
  }
  const res = await apiFetch(`/alerts/${alertId}/resolve`, { method: "PATCH" });
  return res.data;
}
