<?php

use App\Modules\Audit\Infrastructure\Persistence\AuditLog;
use App\Modules\Authentication\Identity\Infrastructure\Persistence\User;
use App\Modules\Observation\Infrastructure\Persistence\Observation;
use App\Modules\Organization\Infrastructure\Persistence\Organization;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Notification;

/**
 * The complete, zero-mock MVP scenario from
 * docs/backend/audit-settings/09-implementation-roadmap.md §6: Organization
 * Registration -> Login -> Create Agent -> Generate API Key -> SDK
 * Observation -> Validation -> Store -> ML -> Prediction -> Alert ->
 * Dashboard -> Observation History — with every step along the way
 * producing a corresponding, correctly-scoped Audit Log entry. The only
 * fake is the outbound HTTP call to the external ML Engine (every module
 * this touches is otherwise exercised for real, exactly like every prior
 * Sprint's own end-to-end test).
 */
test('the full MVP scenario runs end to end, with every step producing a correctly-scoped audit log entry', function () {
    Notification::fake();
    Http::preventStrayRequests();
    Http::fake(['*/analyze' => Http::response([
        'verdict' => 'MALICIOUS',
        'risk_score' => 92,
        'confidence' => 0.95,
        'summary' => 'Credential exfiltration attempt detected.',
        'model_version' => 'sentinelx-ml-1.4.2',
        'reasons' => ['known malicious destination'],
        'evidence' => [['type' => 'event_reference', 'sequence' => 1]],
    ])]);

    // 1. Organization Registration
    $this->postJson('/api/v1/auth/register', [
        'organization_name' => 'MVP Security Co',
        'full_name' => 'MVP Owner',
        'email' => 'mvp-owner@acme.example',
        'password' => 'password123',
        'password_confirmation' => 'password123',
    ])->assertCreated();

    $owner = User::where('email', 'mvp-owner@acme.example')->firstOrFail();
    $organization = Organization::where('name', 'MVP Security Co')->firstOrFail();

    expect(AuditLog::where('organization_id', $organization->id)->where('action', 'user.registered')->count())->toBe(1);

    // Simulate the User clicking the emailed verification link — Login
    // requires a verified email (LoginUserAction), and this scenario is
    // exercising the real login flow next, not verification itself.
    $owner->forceFill(['email_verified_at' => now()])->save();

    // 2. Login
    $this->postJson('/api/v1/auth/login', [
        'email' => 'mvp-owner@acme.example',
        'password' => 'password123',
    ])->assertOk();

    expect(AuditLog::where('organization_id', $organization->id)->where('action', 'user.logged_in')->count())->toBe(1);

    // 3. Create Agent
    $agentResponse = $this->withHeader('Authorization', 'Bearer '.tokenFor($owner))
        ->postJson('/api/v1/agents', ['name' => 'MVP Agent', 'framework' => 'CrewAI'])
        ->assertCreated();

    $agentId = $agentResponse->json('data.id');

    expect(AuditLog::where('organization_id', $organization->id)->where('action', 'agent.created')->count())->toBe(1);

    // 4. Generate API Key
    $keyResponse = $this->withHeader('Authorization', 'Bearer '.tokenFor($owner))
        ->postJson("/api/v1/agents/{$agentId}/rotate-api-key")
        ->assertCreated();

    $rawKey = $keyResponse->json('data.raw_key');

    expect(AuditLog::where('organization_id', $organization->id)->where('action', 'api_key.generated')->count())->toBe(1);

    // 5. SDK sends an Observation (validation + storage happen inline)
    $observationResponse = $this->withHeader('X-Api-Key', $rawKey)
        ->postJson('/api/v1/observations', validAsesPayload())
        ->assertAccepted();

    $observationId = $observationResponse->json('data.id');

    expect(Observation::find($observationId))->not->toBeNull();

    // 6. The Poller claims the Observation and (with the sync queue driver)
    // runs AnalyzeObservationJob inline -> ML -> Prediction -> Alert.
    $this->artisan('analysis:poll-pending-observations')->assertSuccessful();

    $observation = Observation::findOrFail($observationId);
    expect($observation->analysis_status->value)->toBe('COMPLETED');

    // 7. Dashboard reflects the new Agent/Observation/Alert
    $dashboard = $this->withHeader('Authorization', 'Bearer '.tokenFor($owner))
        ->getJson('/api/v1/dashboard')
        ->assertOk();

    expect($dashboard->json('data.organization_stats.total_agents'))->toBe(1)
        ->and($dashboard->json('data.organization_stats.open_alerts'))->toBe(1)
        ->and($dashboard->json('data.risk_summary.MALICIOUS'))->toBe(1);

    // 8. Observation History
    $this->withHeader('Authorization', 'Bearer '.tokenFor($owner))
        ->getJson('/api/v1/observations')
        ->assertOk()
        ->assertJsonPath('data.0.id', $observationId);

    // The Alert generated by the Stage-5 listener
    $alertsResponse = $this->withHeader('Authorization', 'Bearer '.tokenFor($owner))
        ->getJson('/api/v1/alerts')
        ->assertOk()
        ->assertJsonCount(1, 'data');

    $alertId = $alertsResponse->json('data.0.id');

    // 9. Acknowledge and resolve the Alert
    $this->withHeader('Authorization', 'Bearer '.tokenFor($owner))
        ->patchJson("/api/v1/alerts/{$alertId}/acknowledge")
        ->assertOk();

    $this->withHeader('Authorization', 'Bearer '.tokenFor($owner))
        ->patchJson("/api/v1/alerts/{$alertId}/resolve")
        ->assertOk();

    expect(AuditLog::where('organization_id', $organization->id)->where('action', 'alert.acknowledged')->count())->toBe(1)
        ->and(AuditLog::where('organization_id', $organization->id)->where('action', 'alert.resolved')->count())->toBe(1);

    // 10. The full trail is visible via GET /audit-logs
    $auditResponse = $this->withHeader('Authorization', 'Bearer '.tokenFor($owner))
        ->getJson('/api/v1/audit-logs')
        ->assertOk();

    $actions = collect($auditResponse->json('data'))->pluck('action');

    expect($actions)->toContain('user.registered')
        ->toContain('user.logged_in')
        ->toContain('agent.created')
        ->toContain('api_key.generated')
        ->toContain('alert.acknowledged')
        ->toContain('alert.resolved');

    // Observation/Prediction storage are deliberately never audited — see
    // adr/ADR-002-audit-scoped-to-human-initiated-actions.md.
    expect($actions)->not->toContain('observation.received')
        ->and($actions)->not->toContain('prediction.stored');

    // 11. Security Logs surfaces only the security-relevant subset
    $securityResponse = $this->withHeader('Authorization', 'Bearer '.tokenFor($owner))
        ->getJson('/api/v1/security-logs')
        ->assertOk();

    $securityActions = collect($securityResponse->json('data'))->pluck('action');

    expect($securityActions)->toContain('user.registered')
        ->toContain('user.logged_in')
        ->toContain('api_key.generated')
        ->and($securityActions)->not->toContain('agent.created')
        ->and($securityActions)->not->toContain('alert.acknowledged');
});
