<?php

use App\Modules\Authentication\Identity\Infrastructure\Persistence\User;
use App\Modules\Observation\Infrastructure\Persistence\Observation;
use App\Modules\Organization\Infrastructure\Persistence\Organization;
use Illuminate\Support\Facades\Http;

/**
 * RC-3 / DATAFLOW-002 / WALK-003: proves evidence/reasons survive the full
 * origin-to-consumer journey -- generated by the (fake, but realistically
 * shaped per Phase 2's settled envelope) ML response, stored verbatim in
 * prediction_json, and read back out through every API surface a real
 * Frontend page consumes. This is a Resource/storage-layer proof, not a
 * live-ML-wire proof -- Phase 2's own LiveMlServiceIntegrationTest already
 * covers the ML Service genuinely producing these fields over real HTTP;
 * this test's job is confirming the Backend doesn't drop them afterward,
 * which was the entire, exhaustively-confirmed defect DATAFLOW-002
 * described.
 */
test('reasons and evidence generated by the ML response survive to every consuming API endpoint', function () {
    Http::preventStrayRequests();

    $reasons = [
        'Prompt injection attempt detected in LLM API call',
        'Sensitive file accessed outside expected scope',
    ];
    $evidence = [
        [
            'sequence' => 0,
            'event_type' => 'api_call',
            'evidence_type' => 'Prompt Injection',
            'description' => 'The input matched known prompt injection patterns.',
            'reference' => 'HF-PROMPT-INJECTION',
            'confidence' => 0.946,
        ],
        [
            'sequence' => 1,
            'event_type' => 'file_access',
            'evidence_type' => 'Threat Match',
            'description' => 'Event matched known pattern: Excessive Agency Exploitation.',
            'reference' => 'AML.T0054',
            'confidence' => null,
        ],
    ];

    Http::fake(['*/analyze' => Http::response([
        'verdict' => 'MALICIOUS',
        'risk_score' => 92,
        'confidence' => 0.95,
        'summary' => 'Known exfiltration pattern.',
        'model_version' => 'sentinelx-ml-1.4.2',
        'reasons' => $reasons,
        'evidence' => $evidence,
    ])]);

    $organization = Organization::factory()->create();
    $owner = User::factory()->owner()->for($organization)->create();
    $observation = Observation::factory()->for($organization)->create();

    $this->artisan('analysis:poll-pending-observations')->assertSuccessful();
    $token = 'Bearer '.tokenFor($owner);

    // GET /alerts (list) -- AlertSummaryResource: reasons only.
    $listResponse = $this->withHeader('Authorization', $token)
        ->getJson('/api/v1/alerts')
        ->assertOk()
        ->assertJsonCount(1, 'data')
        ->assertJsonPath('data.0.reasons', $reasons);
    $alertId = $listResponse->json('data.0.id');

    // GET /alerts/{id} (detail) -- PredictionDetailResource: reasons AND evidence.
    $this->withHeader('Authorization', $token)
        ->getJson("/api/v1/alerts/{$alertId}")
        ->assertOk()
        ->assertJsonPath('data.prediction.reasons', $reasons)
        ->assertJsonPath('data.prediction.evidence', $evidence);

    // GET /observations/{id} -- PredictionSummaryResource: reasons.
    $this->withHeader('Authorization', $token)
        ->getJson("/api/v1/observations/{$observation->id}")
        ->assertOk()
        ->assertJsonPath('data.prediction.reasons', $reasons)
        // Confirms PredictionSummaryResource specifically, not the fuller
        // Resource -- evidence must NOT leak into this embed.
        ->assertJsonMissingPath('data.prediction.evidence');

    // GET /dashboard -- recent_alerts: reasons.
    $this->withHeader('Authorization', $token)
        ->getJson('/api/v1/dashboard')
        ->assertOk()
        ->assertJsonPath('data.recent_alerts.0.reasons', $reasons);
});

test('an Alert whose Prediction carries no reasons/evidence (a genuinely empty ML response) exposes empty arrays, not an error', function () {
    Http::preventStrayRequests();
    Http::fake(['*/analyze' => Http::response([
        'verdict' => 'SUSPICIOUS',
        'risk_score' => 60,
        'confidence' => 0.7,
        'summary' => 'Borderline signal.',
        'model_version' => 'sentinelx-ml-1.4.2',
        // Deliberately no reasons/evidence keys -- not validated fields
        // (MLResponseValidator never requires them), so a real ML response
        // could genuinely omit them.
    ])]);

    $organization = Organization::factory()->create();
    $owner = User::factory()->owner()->for($organization)->create();
    Observation::factory()->for($organization)->create();

    $this->artisan('analysis:poll-pending-observations')->assertSuccessful();

    $response = $this->withHeader('Authorization', 'Bearer '.tokenFor($owner))
        ->getJson('/api/v1/alerts')
        ->assertOk()
        ->assertJsonPath('data.0.reasons', []);
    $alertId = $response->json('data.0.id');

    $this->withHeader('Authorization', 'Bearer '.tokenFor($owner))
        ->getJson("/api/v1/alerts/{$alertId}")
        ->assertOk()
        ->assertJsonPath('data.prediction.reasons', [])
        ->assertJsonPath('data.prediction.evidence', []);
});
